### ISSUE TITLE
Not working with pyproject.toml

### ISSUE THREAD

**Issue by igormcsouza** [AndreMiras/coveralls-python-action#18]
Hello! Thank you for your wonderful job! I had troubles using the pyproject.toml version as explained here <https://github.com/marketplace/actions/coveralls-python#pyprojecttoml>. I tried everything. I installed coverage with [toml] extra, but it stills output the message..

```
Can't read 'pyproject.toml' without TOML support. Install with [toml] extra
```

Any ideas on the matter? It's working fine now I'm using .coveragerc file! But I really want to use the pyproject.tom versionl!!

This is the repo if will help (https://github.com/igormcsouza/pymetaheuristics)

**Comment by igormcsouza** [comment]
I just see this PR < https://github.com/AndreMiras/coveralls-python-action/pull/16 > might be the solution!!!

**Comment by mcarans** [comment]
I hope that PR will be merged soon assuming it works.

**Comment by adrienverge** [comment]
Hello, I have the same problem.

The workaround I found is to dynamically create a temporary `.coveragerc` file. For example:
```yaml
      - run: pip install coverage
      # Workaround for https://github.com/AndreMiras/coveralls-python-action/issues/18
      - run: echo -e "[run]\nrelative_files = True" > .coveragerc
      - run: coverage run -m unittest discover
      - name: Coveralls
        uses: AndreMiras/coveralls-python-action@develop
```
