### ISSUE TITLE
Instructions for pyproject.toml not working for me

### ISSUE THREAD

**Issue by mcarans** [AndreMiras/coveralls-python-action#20]
The README says "It also requires coverage to be installed with the toml extra (pip install coverage[toml]):"

I tried the following:

```
    - name: Install coverage dependency
      run: pip install --upgrade coverage[toml]
    - name: Publish in Coveralls
      uses: AndreMiras/coveralls-python-action@develop
      if: success()
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        flag-name: tests
```

I got "Can't read 'pyproject.toml' without TOML support. Install with [toml] extra"

How do I make this work?
