### ISSUE TITLE
"No build matching CI build number " when including non-Linux jobs

### ISSUE THREAD

**Issue by hugovk** [AndreMiras/coveralls-python-action#23]
Currently I have a number of Ubuntu jobs which run in parallel `max-parallel: 1`.

They each have this step:

```yml
      - name: Coveralls
        uses: AndreMiras/coveralls-python-action@develop
        with:
          parallel: true
```

And then there's a final job to bring them together:

```yml
  coveralls_finish:
    needs: tests
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls finished
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel-finished: true
```

Full workflow: https://github.com/python-twitter-tools/twitter/blob/fbc7aa50a9f146d50ba3d7a8ea50ae37ac220715/.github/workflows/tests.yml

This is working fine.

---

However, I wish to add one macOS jon and one Windows job, to cover the differing behaviour on other operating systems:

```yml
        include:
          # Test Windows and macOS on other 3.x versions
          - { python-version: "3.8", os: "windows-latest" }
          - { python-version: "3.9", os: "macos-latest" }
```

And because `AndreMiras/coveralls-python-action` only runs on Linux, added this `if` guard to this step:

```yml
        # Linux only
      - name: Coveralls
        if: matrix.is == 'ubuntu-latest'
        uses: AndreMiras/coveralls-python-action@develop
        with:
          parallel: true
```

Full worflow: https://github.com/hugovk/twitter/blob/25e55ffa88b5117e6f138070fd60e566ff908979/.github/workflows/tests.yml
See PR: https://github.com/python-twitter-tools/twitter/pull/453

But the final step is failing with:

```
{'error': 'No build matching CI build number 3058929957 found'}
Traceback (most recent call last):
  File "/src/entrypoint.py", line 176, in try_main
    main()
  File "/src/entrypoint.py", line 169, in main
    post_webhook(repo_token)
  File "/src/entrypoint.py", line [12](https://github.com/python-twitter-tools/twitter/actions/runs/3058929957/jobs/4937995078#step:3:13)2, in post_webhook
    assert result.get("done", False), result
AssertionError: {'error': 'No build matching CI build number 3058929957 found'}
ExitCode.FAILURE
```

For example: https://github.com/python-twitter-tools/twitter/actions/runs/3058929957/jobs/4937995078

How can I use this when testing non-Linux jobs?

Thank you!
