### ISSUE TITLE
parallel pull requests fail

### ISSUE THREAD

**Issue by casperdcl** [AndreMiras/coveralls-python-action#7]
using

```yaml
  test:
    ...
    - uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel: true
  finish:
    ...
    - uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel-finished: true
```

works for `push` (e.g. https://github.com/casperdcl/git-fame/pull/48/checks?check_run_id=1403032487)

but exactly the same code fails for `pull_request` (e.g. https://github.com/casperdcl/git-fame/pull/48/checks?check_run_id=1403032586):

```
{'error': 'No build matching CI build number 6e40a87c6b739928b6727d3bb8724ebdff450e79-PR-48 found'}
```

so this must be wrong, but I'm not sure where the correct API/build_number would be documented: https://github.com/AndreMiras/coveralls-python-action/blob/f10e25f1a5708d823d4db7e4d6ea32d9634d8c89/src/entrypoint.py#L102-L103

CC @exoplanet-dev from #5
